export {
  BUILD_ACTIONS,
  DISCARD_THRESHOLD,
  FAME_MEDAL_PIECES_PER_POINT,
  getBuildCost,
  getMothershipUpgradeLimit,
  getReserveDrawEntitlement,
  getSupplyTradeRate,
  GOODS_SUPPLY_TRADE_RATE,
  MOTHERSHIP_UPGRADE_KINDS,
  RESERVE_CARDS_PER_RESOURCE,
  SETUP_RESERVE_DRAW_COUNT,
  STANDARD_SUPPLY_TRADE_RATE,
  STARTING_VICTORY_POINTS,
  VICTORY_POINT_TARGET,
  VICTORY_POINT_VALUES,
  type BuildAction,
  type MothershipUpgradeKind,
} from './rules-config'
